Добавлен метод для задании роли (только для UserRole.NeedSetRole)
WorkQuest/backend-development pull request #17
Opened 2021-06-03 11:43 UTC by Microsxema

Добавлен ключ UserRole.NeedSetRole
Login через соц.сети: при новом пользователе UserRole = NeedSetRole

2021-06-03 17:31 UTC, mdenushev requested changes
Также необходимо разрешить в обработчике авторизации вызывать этот метод, если статус не Confirmed

2021-06-03 17:31 UTC, mdenushev commented on src/server/api/profile.ts
> +  if (user.status !== UserStatus.NeedSetRole && Object.values(UserRole).includes(r.payload.role)) {
Какая-то странная проверка, видимо, ты имел ввиду "Если у пользователя не статус NeedSetRole или у пользователя роль не null"

2021-06-03 17:31 UTC, mdenushev commented on src/server/api/profile.ts
> +    return error(Errors.InvalidPayload, 'User is not need set role', {});
"User don\'t need to set role"

2021-06-04 02:16 UTC, Microsxema commented on src/server/api/profile.ts
> +  if (user.status !== UserStatus.NeedSetRole && Object.values(UserRole).includes(r.payload.role)) {
А если там будет пустая строка, а не null, или любой другой мусор. Поэтому поставил так => Если у пользователя не статус NeedSetRole ИЛИ (тут опечатка была, исправлю на или)  роль == (исполнитель, работодатель).

2021-06-04 09:39 UTC, mdenushev approved these changes

2021-06-07 03:22 UTC, merged