Доблена авторизация через соцсети
WorkQuest/backend-development pull request #8
Opened 2021-05-27 05:00 UTC by Microsxema

2021-05-28 09:58 UTC, mdenushev requested changes

2021-05-28 09:58 UTC, mdenushev commented on src/server/api/auth.ts
> +					facebook: {
у тебя все соцсети facebook будут?

2021-05-28 09:58 UTC, mdenushev commented on src/server/index.ts
> +function initSocialNetwork(server: Hapi.Server) {
переименнуй функцию, чтобы понятнее было

2021-05-28 09:58 UTC, mdenushev commented on src/server/index.ts
> +    password: 'cookie_encryption_password_secure',
password для каждой из соцсетей должен быть разный

2021-05-28 09:58 UTC, mdenushev commented on src/server/index.ts
> +    clientId: config.socialNetworks.facebook.id || 'null',
убери `|| 'null'` потому что потом могут выскочить косяки, если с конфига не стянутся

2021-05-28 09:58 UTC, mdenushev commented on src/server/api/auth.ts
> +export async function loginThroughSocialNetwork(r) {
что-то какие-то гигантские отступы, посмотри какие у тебя стоят в ide

2021-05-28 09:58 UTC, mdenushev commented on src/server/config/config.ts
> +      id: process.env.FACEBOOK_CLIENT_ID,
если добавил переменные в конфиг, то надо добавить в `ci-scripts/roles/backend-update/.env.j2` и скидывать переменные мне, чтобы я добавил в github secrets

2021-05-28 09:58 UTC, mdenushev commented on package.json
> +    "i": "^0.3.6",
это что за зависимость?

2021-05-31 03:54 UTC, Microsxema commented on src/server/api/auth.ts
> +					facebook: {
Да

2021-05-31 12:39 UTC, mdenushev approved these changes

2021-05-31 12:40 UTC, merged